apiVersion: apps/v1
kind: Deployment
metadata:
  name: itinerary-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itinerary-app
  template:
    metadata:
      labels:
        app: itinerary-app
    spec:
      containers:
      - name: itinerary-app
        image: gcr.io/concierge-miami/itinerary:118
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10